### ISSUE TITLE
Training Monitor - Übergabe der loss function an das Frontend

### ISSUE THREAD

**Issue by TheTolpan** [TheTolpan/EaseML#12]

**Comment by mertyaylacigit** [comment]
@sintokk du kanst jetzt wie data.acc auch data.loss bekommen
Ich habe den Port auf 5001, da bei Niklas und Phillip andere Prozesse auf 5000 liefen (iOS).
Wir können easy neue Metriken wie z.B. recall oder f1 hinzufügen, wobei man diese dann auch noch in training.py ausrechnen muss.
