### ISSUE TITLE
Setting up our Git

### ISSUE THREAD

**Issue by TheTolpan** [TheTolpan/EaseML#2]
Root Directory:

    README.md: Eine detaillierte Einführung in das Projekt, seinen Zweck, seine Funktionen und Anweisungen zur Installation und Nutzung.
    LICENSE: Eine Lizenzdatei, die angibt, wie das Projekt verwendet werden darf.
    .gitignore: Eine Liste von Dateitypen und Ordnern, die von Git ignoriert werden sollten (z.B. temporäre Dateien, IDE-spezifische Dateien).

Dokumentationsverzeichnis (/docs):

    Enthält alle projektbezogenen Dokumente, wie Spezifikationen, Design-Dokumente und Meeting-Protokolle.
    project_concept.md: Eine detaillierte Beschreibung des Projektkonzepts.
    development_plan.md: Ein Entwicklungsplan mit Zeitplan, Meilensteinen und Verantwortlichkeiten.
    wireframes/: Ein Unterverzeichnis für Wireframe-Bilder oder -Dateien.

Quellcodeverzeichnisse:

    /src: Der Hauptquellcode des Projekts.
    /tests: Enthält Tests für den Quellcode.

Verzeichnis für Konfigurationsdateien (/config):

    Konfigurationsdateien für verschiedene Umgebungen (Entwicklung, Test, Produktion).

Ressourcenverzeichnis (/resources):

    Grafiken, Daten und andere Ressourcen, die das Projekt benötigt.

Skripte (/scripts):

    Nützliche Skripte für das Setup, die Datenmigration, usw.

Dependencies:

    requirements.txt oder package.json (abhängig von der verwendeten Programmiersprache/Technologie): Listen Sie alle externen Bibliotheken und Frameworks auf, die das Projekt benötigt.

**Comment by jniklasklein** [comment]
Done

**Comment by mertyaylacigit** [comment]
jo danke, ich packe meinen code in src/ da rein, wo ich denke dass es hingehört, erstmal aber in meinem dev_Mert branch.
